version: "3"

services:

  etracs-server:
    container_name: etracs-server
    image: ramesesinc/etracs25-server-city:255.02.007
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: 10m
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ./env.conf
      - ../../_custom/env.conf
    ports:
      - "8070:8070"
    volumes:
      - ./modules:/apps/etracs25/modules
      - ../../_res/connections:/apps/etracs25/connections/ext      
      - ../../_custom/module-server:/apps/etracs25/modules/ext/zzz-lgu-custom-module

      - ../../temp/etracs:/services/modules

      - ./dev_modules/gov:/gov
      - ./dev_modules/gov/etracs__gov.conf:/apps/etracs25/modules.conf.d/etracs__gov.conf

      - ./dev_modules/rptis:/rptis
      - ./dev_modules/rptis/etracs_rptis.conf:/apps/etracs25/modules.conf.d/etracs_rptis.conf
